### ISSUE TITLE
ComplexDouble error when using for DiffSinger

### ISSUE THREAD

**Issue by hilmiyafia** [yxlllc/pc-ddsp#2]
Hello, I've trained a ddsp model and put it in the diffsinger checkpoints folder. At the validation step it errors:

Traceback (most recent call last):
  File "/content/DiffSinger/run.py", line 15, in <module>
    run_task()
  File "/content/DiffSinger/run.py", line 11, in run_task
    task_cls.start()
  File "/content/DiffSinger/basics/base_task.py", line 242, in start
    trainer.fit(task)
  File "/content/DiffSinger/utils/pl_utils.py", line 497, in fit
    self.run_pretrain_routine(model)
  File "/content/DiffSinger/utils/pl_utils.py", line 573, in run_pretrain_routine
    self.evaluate(model, self.get_val_dataloaders(), self.num_sanity_val_steps, self.testing)
  File "/content/DiffSinger/utils/pl_utils.py", line 1193, in evaluate
    output = self.evaluation_forward(model,
  File "/content/DiffSinger/utils/pl_utils.py", line 1317, in evaluation_forward
    output = model.validation_step(*args)
  File "/content/DiffSinger/src/naive_task.py", line 85, in validation_step
    self.plot_wav(batch_idx, sample['mels'], model_out['mel_out'], gt_f0=gt_f0, pred_f0=pred_f0)
  File "/content/DiffSinger/src/diffspeech_task.py", line 120, in plot_wav
    gt_wav = self.vocoder.spec2wav(gt_mel, f0=gt_f0)
  File "/content/DiffSinger/src/vocoders/ddsp.py", line 163, in spec2wav
    signal, _, (s_h, s_n) = self.model(mel.to(self.device), f0.to(self.device))
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
RuntimeError: Unsupported value kind: ComplexDouble

**Comment by yxlllc** [comment]
I guess ComplexDouble is supported in higher version of pytorch.

**Comment by hilmiyafia** [comment]
@yxlllc Thank you! It's working now! 😊
